### ISSUE TITLE
Separate server repo and client repo

### ISSUE THREAD

**Issue by jollyra** [supermitch/mech-ai#1]
There are some benefits to having separate repos for the server and the client. Once the code grows a bit the server could be broken off, and easily installed + configured via a npm package with a dependency list.

**Comment by supermitch** [comment]
Sounds good. If that's the architecture we wanna go with.

**Comment by jollyra** [comment]
Like, you said, the server is the whole game. So the repo already is the server. I didn't know what I was talking about.

**Comment by supermitch** [comment]
I think eventually we will separate them again. The server really will have nothing to do with the client. I don't know the value of maintaining two repos, but it'll be much more clear. I guess things like collaborators and stuff. People may want to work on the client and others will want to work on the server, and the two are totally independent.

**Comment by supermitch** [comment]
I think having them in the same repo makes sense. One benefit is that seeing changes (history) in git will show updates to both at once. If the repos are split, that linkage is lost. I see no real benefit to two repos, unless they are enormous and git can't handle it. (Which is def. never going to be the case.) Going to close this issue.
